services:
  - type: web
    name: Fastapi-GuessingGame
    runtime: python            
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:main --host 0.0.0.0 --port 10000"
